-- =========================================================================
-- SCIMAX INDUSTRIES - SUPABASE DATABASE SCHEMA & POLICIES
-- Project ID: kuqxzvewvrdbcgzfakcp
-- =========================================================================

-- 1. Create INQUIRIES Table (For Website RFQ & Contact Submissions)
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    industry TEXT DEFAULT '',
    product_interest TEXT NOT NULL,
    message TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on inquiries
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Allow public anonymous visitors to submit inquiries / RFQs
CREATE POLICY "Allow anonymous inquiry insert" 
ON public.inquiries 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Allow authenticated / service-role users to read inquiries
CREATE POLICY "Allow service role read inquiries" 
ON public.inquiries 
FOR SELECT 
TO service_role 
USING (true);


-- 2. Create CLIENTS Table (For Industrial Clientele & Installations)
CREATE TABLE IF NOT EXISTS public.clients (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    sector TEXT NOT NULL,
    location TEXT NOT NULL,
    equipment_installed TEXT NOT NULL,
    capacity TEXT NOT NULL,
    year_installed INT NOT NULL,
    featured BOOLEAN DEFAULT false,
    verified BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on clients
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

-- Allow public anonymous read access to clients directory
CREATE POLICY "Allow public read clients" 
ON public.clients 
FOR SELECT 
TO anon, authenticated 
USING (true);

-- Allow service role to manage clients
CREATE POLICY "Allow service role manage clients" 
ON public.clients 
FOR ALL 
TO service_role 
USING (true);


-- 3. Initial Seed Data: 16 Enterprise Industrial Clients
INSERT INTO public.clients (id, name, sector, location, equipment_installed, capacity, year_installed, featured, verified)
VALUES
    ('tata-steel', 'Tata Steel Limited', 'Steel & Metallurgy', 'Jamshedpur & Gujarat', 'High Pressure ID Fans & Cyclone Separators', '6,50,000 m³/hr', 2021, true, true),
    ('ultratech-cement', 'UltraTech Cement', 'Cement & Minerals', 'Kovaya, Gujarat', 'Pulse-Jet Baghouse Filtration System', '1,20,000 CFM', 2022, true, true),
    ('aarti-industries', 'Aarti Industries Ltd.', 'Specialty Chemicals', 'Vapi & Jhagadia, Gujarat', 'Corrosion-Resistant Fume Extraction & Scrubbers', '45,000 CFM', 2023, true, true),
    ('ambuja-cements', 'Ambuja Cements Ltd.', 'Cement & Minerals', 'Ambujanagar, Gujarat', 'Heavy Duty Clinker Cooler FD Blowers', '3,20,000 m³/hr', 2020, true, true),
    ('jindal-steel', 'Jindal Steel & Power', 'Steel & Metallurgy', 'Angul & Baroda', 'Induction Furnace Fume Extraction System', '85,000 CFM', 2022, true, true),
    ('atul-limited', 'Atul Limited', 'Chemicals & Dyes', 'Valsad, Gujarat', 'SS316 Acid Vapor Exhaust Blowers & Ducting', '35,000 CFM', 2021, true, true),
    ('zydus-lifesciences', 'Zydus Lifesciences', 'Pharma & API', 'Changodar, Ahmedabad', 'cGMP Stainless Cartridge Dust Collectors', '18,000 CFM', 2023, true, true),
    ('torrent-power', 'Torrent Power', 'Power & Energy', 'Surat & Ahmedabad, Gujarat', 'Flue Gas Induced Draft Fans (ISO 1940 G6.3)', '4,50,000 m³/hr', 2020, true, true),
    ('adani-wilmar', 'Adani Wilmar Ltd.', 'Food & Agro Processing', 'Mundra, Gujarat', 'Grain Silo Vent Filters & High-Efficiency Cyclones', '28,000 CFM', 2022, true, true),
    ('kajaria-ceramics', 'Kajaria Ceramics', 'Ceramics & Tiles', 'Morbi, Gujarat', 'Spray Dryer Dust Recovery Baghouse', '95,000 CFM', 2021, true, true),
    ('asian-granito', 'Asian Granito India Ltd.', 'Ceramics & Tiles', 'Himmatnagar, Gujarat', 'Raw Material Batching Dust Extraction', '42,000 CFM', 2023, false, true),
    ('arvind-mills', 'Arvind Limited', 'Textiles & Denim', 'Naroda, Ahmedabad', 'Centralized Textile Lint & Dust Filtration', '60,000 CFM', 2020, true, true),
    ('welspun-corp', 'Welspun Corp', 'Heavy Engineering', 'Anjar, Gujarat', 'Shot Blasting Dust Collection & Cartridge Units', '55,000 CFM', 2021, false, true),
    ('deep-industries', 'Deep Industries Ltd.', 'Oil & Gas Energy', 'Ahmedabad, Gujarat', 'Flameproof Bifurcated Exhaust Blowers', '30,000 CFM', 2022, false, true),
    ('nirma-chemicals', 'Nirma Limited', 'Chemicals & Detergents', 'Bhavnagar, Gujarat', 'Rotary Calcinator Dust Recovery System', '50,000 CFM', 2022, false, true),
    ('upl-limited', 'UPL Limited', 'Agrochemicals', 'Jhagadia, Gujarat', 'Multi-Venturi Scrubbers & Hazardous Vapor Fans', '25,000 CFM', 2023, false, true)
ON CONFLICT (id) DO NOTHING;
